# Generated by Django 4.0.4 on 2022-05-29 03:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BagType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('boxType', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('miscCharges', models.IntegerField(default=0)),
            ],
        ),
    ]
