# Generated by Django 4.0.5 on 2022-06-13 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscPackaging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('cost', models.FloatField(default=0)),
                ('boxChargeChile', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='styles',
            name='boxTypes',
            field=models.ManyToManyField(to='charge.boxdifference'),
        ),
        migrations.CreateModel(
            name='LaborCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('people', models.IntegerField(default=0)),
                ('bagsPerMinute', models.IntegerField(default=0)),
                ('wagesPerHour', models.FloatField(default=0)),
                ('bagType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charge.bagtype')),
            ],
        ),
    ]
