# Generated by Django 4.0.5 on 2022-06-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0002_miscpackaging_styles_boxtypes_laborcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styles',
            name='countSize',
        ),
    ]
