# Generated by Django 4.0.5 on 2022-07-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0002_remove_bagcost_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='bagSize',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
