# Generated by Django 4.0.5 on 2022-06-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_remove_styles_countsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='styles',
            name='countSize',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
