# Generated by Django 4.0.5 on 2022-07-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_alter_styles_bagsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='bagSize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='styles',
            name='twb_flag',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False, null=True),
        ),
    ]
