# Generated by Django 4.0.4 on 2022-05-29 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_bagcost_baglength_bagcost_bagweight_bagcost_boxtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagcost',
            name='boxType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charge.boxtype'),
        ),
    ]
