# Generated by Django 4.0.5 on 2022-06-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0004_styles_countsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='twb_flag',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
