# Generated by Django 4.0.4 on 2022-05-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0004_alter_bagcost_boxtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagcost',
            name='bagLength',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bagcost',
            name='bagWeight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bagcost',
            name='costPerBag',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bagcost',
            name='laborCost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bagcost',
            name='totalCost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bagcost',
            name='wastePercentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='boxtype',
            name='miscCharges',
            field=models.FloatField(default=0),
        ),
    ]
