# Generated by Django 4.0.5 on 2022-06-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0005_alter_styles_twb_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodities',
            name='pricePerPound',
            field=models.FloatField(default=0),
        ),
    ]
