# Generated by Django 4.0.4 on 2022-05-30 22:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0006_packagingcosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('avgCtnPrice', models.FloatField(default=0)),
                ('stdCtnCost', models.FloatField(default=0)),
                ('netWeightChile', models.FloatField(default=0)),
                ('netWeightDomestic', models.FloatField(default=0)),
                ('packingCharge', models.FloatField(default=0)),
                ('pallets', models.FloatField(default=0)),
                ('profitPerBag', models.FloatField(default=0)),
                ('promo', models.FloatField(default=0)),
            ],
        ),
    ]
