# Generated by Django 4.0.5 on 2022-06-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0006_commodities_priceperpound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodities',
            name='profitPerBag',
            field=models.FloatField(default=0, null=True),
        ),
    ]
