# Generated by Django 4.0.5 on 2022-06-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0007_alter_commodities_profitperbag'),
    ]

    operations = [
        migrations.AddField(
            model_name='styles',
            name='referring_miscPackaging',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charge.miscpackaging'),
        ),
    ]
