# Generated by Django 4.0.1 on 2022-07-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0007_constants_alter_styles_boxtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styles',
            name='boxTypes',
        ),
    ]
