# Generated by Django 4.0.1 on 2022-07-28 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0008_remove_styles_boxtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='styles',
            name='miscPackaging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charge.miscpackaging'),
        ),
    ]
