# Generated by Django 4.0.4 on 2022-06-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0009_styles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoxType',
            new_name='BagType',
        ),
        migrations.RenameField(
            model_name='bagcost',
            old_name='boxType',
            new_name='bagType',
        ),
        migrations.RenameField(
            model_name='bagtype',
            old_name='boxType',
            new_name='bagType',
        ),
        migrations.RenameField(
            model_name='packagingcosts',
            old_name='boxType',
            new_name='bagType',
        ),
        migrations.RenameField(
            model_name='styles',
            old_name='boxType',
            new_name='bagType',
        ),
    ]
