# Generated by Django 4.0.1 on 2022-07-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0009_styles_miscpackaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styles',
            name='miscPackaging',
        ),
        migrations.AddField(
            model_name='styles',
            name='miscPackaging',
            field=models.ManyToManyField(to='charge.MiscPackaging'),
        ),
    ]
