# Generated by Django 4.0.5 on 2022-06-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0010_alter_styles_referring_miscpackaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='referring_miscPackaging',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='charge.miscpackaging'),
        ),
    ]
