# Generated by Django 4.0.5 on 2022-07-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0010_remove_styles_miscpackaging_styles_miscpackaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='miscPackaging',
            field=models.ManyToManyField(related_name='miscPackaging_rel', to='charge.miscpackaging'),
        ),
    ]
