# Generated by Django 4.0.1 on 2022-07-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0011_alter_styles_miscpackaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='miscPackaging',
            field=models.ManyToManyField(blank=True, related_name='miscPackaging_rel', to='charge.MiscPackaging'),
        ),
    ]
