# Generated by Django 4.0.5 on 2022-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0011_styles_bagcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='bagCost',
            field=models.IntegerField(),
        ),
    ]
