# Generated by Django 4.0.5 on 2022-06-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0012_alter_styles_bagcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styles',
            name='bagCost',
        ),
    ]
