# Generated by Django 4.0.5 on 2022-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0012_remove_styles_referring_miscpackaging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingcosts',
            name='labelCost',
            field=models.FloatField(default=0),
        ),
    ]
