# Generated by Django 4.0.5 on 2022-06-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0013_packagingcosts_labelcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styles',
            name='referring_miscPackaging',
        ),
    ]
