# Generated by Django 4.0.5 on 2022-06-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0013_remove_styles_bagcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='styles',
            name='bagCost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charge.bagcost'),
        ),
    ]
