# Generated by Django 4.0.5 on 2022-06-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0014_styles_bagcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='styles',
            old_name='bagCost',
            new_name='referring_bagCost',
        ),
    ]
