# Generated by Django 4.0.5 on 2022-06-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0015_rename_bagcost_styles_referring_bagcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='referring_bagCost',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='charge.bagcost'),
        ),
    ]
