# Generated by Django 4.0.5 on 2022-06-02 17:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0016_alter_styles_referring_bagcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxDifference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('boxDiff', models.FloatField(default=0)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
    ]
