# Generated by Django 4.0.5 on 2022-06-03 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0017_boxdifference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('cost', models.FloatField(default=0)),
            ],
        ),
    ]
